### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute '17'

### ISSUE THREAD

**Issue by Msaif2299** [sniklaus/3d-ken-burns#16]
After watching a video on this, I immediately looked up to find this repository. I am very excited for it to work but I am encountering this issue, and I can't seem to resolve this.

Currently have:
pytorch 1.4.0
python 3.7.3 64-bit
cupy 7.1.0
moviepy 1.0.1

3d-ken-burns-master\3d-ken-burns-master>python autozoom.py --in ./images/doublestrike.jpg --out ./autozoom.mp4
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "autozoom.py", line 45, in <module>
    exec(open('./models/disparity-estimation.py', 'r').read())
  File "<string>", line 194, in <module>
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\__init__.py", line 1456, in init_then_script
    self.__dict__["_actual_script_module"] = torch.jit._recursive.create_script_module(self, stubs)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\_recursive.py", line 336, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\__init__.py", line 1593, in _construct
    init_fn(script_module)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\_recursive.py", line 328, in init_fn
    scripted = recursive_script(orig_value)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\_recursive.py", line 336, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\__init__.py", line 1593, in _construct
    init_fn(script_module)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\_recursive.py", line 328, in init_fn
    scripted = recursive_script(orig_value)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\_recursive.py", line 336, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\__init__.py", line 1593, in _construct
    init_fn(script_module)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\_recursive.py", line 321, in init_fn
    orig_value = getattr(nn_module, name)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute '17'

**Comment by sniklaus** [comment]
This issue should be fixed in the most recent commit, please consider trying the new version. I am closing this issue for now, feel free to reopen in case the problem still persists.
