### ISSUE TITLE
Attempting to read a .pytorch file instead of a .py file

### ISSUE THREAD

**Issue by Msaif2299** [sniklaus/3d-ken-burns#18]
Hi! Can I get a solution to this error? I can't seem to find anything online for this either.

>python autozoom.py --in ./images/doublestrike.jpg --out ./autozoom.mp4
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "autozoom.py", line 45, in <module>
    exec(open('./models/disparity-estimation.py', 'r').read())
  File "<string>", line 195, in <module>
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\msaif\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/disparity-estimation.pytorch'

**Comment by sniklaus** [comment]
Seems like the pre-trained model is missing, did you follow the steps outlined in the setup section?

**Comment by redreamality** [comment]
If you download the models using other tools other than the provided ` download.bash `,
remember to change filename according to the bash file.
