### ISSUE TITLE
Strange error - probably not you

### ISSUE THREAD

**Issue by GantMan** [sniklaus/3d-ken-burns#3]
It seems to depend on samples helper_math.h but doesn't know where to find it?

```
(base) PS C:\Users\Owner\Desktop\Code\ML\3d-ken-burns> python autozoom.py --in ./images/doublestrike.jpg --out ./autozoom.mp4
Traceback (most recent call last):
  File "C:\Users\Owner\Anaconda3\lib\site-packages\cupy\cuda\compiler.py", line 242, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy\cuda\nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy\cuda\nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy\cuda\nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autozoom.py", line 87, in <module>
    'objectFrom': objectFrom
  File "<string>", line 116, in process_autozoom
  File "<string>", line 443, in render_pointcloud
  File "cupy\util.pyx", line 55, in cupy.util.memoize.decorator.ret
  File "<string>", line 306, in launch_kernel
  File "C:\Users\Owner\Anaconda3\lib\site-packages\cupy\cuda\compiler.py", line 165, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch, name + '.cu')
  File "C:\Users\Owner\Anaconda3\lib\site-packages\cupy\cuda\compiler.py", line 81, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "C:\Users\Owner\Anaconda3\lib\site-packages\cupy\cuda\compiler.py", line 246, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: C:\Users\Owner\AppData\Local\Temp\tmpu807esdp\6e7e4513b4a6c2bb9216b74b496c77b7_2.cubin.cu(2): catastrophic error: cannot open source file "samples/common/inc/helper_math.h"

1 catastrophic error detected in the compilation of "C:\Users\Owner\AppData\Local\Temp\tmpu807esdp\6e7e4513b4a6c2bb9216b74b496c77b7_2.cubin.cu".
Compilation terminated.
```

I verified the samples exist here: C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1

**Comment by GantMan** [comment]
Your code depends on the samples files for CUDA.  These install to a different folder on Windows.

I had to copy the contents of `C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1` to my CUDA_HOME under a folder named `samples` for the project to run.

**Comment by sniklaus** [comment]
My apologies for the trouble. I noticed this the other day when I was running it on Windows too but I didn't have a good solution to target both platforms. I may change the code to download the "helper_math.h" directly from Nvidia when necessary.

**Comment by emilwallner** [comment]
This worked for me:

```
cd /usr/local/cuda
git clone https://github.com/NVIDIA/cuda-samples.git samples
mv samples/Common samples/common
mkdir samples/common/inc
mv samples/common/*.h samples/common/inc
```
