### ISSUE TITLE
after git，the another issue happen

### ISSUE THREAD

**Issue by 834799106** [sniklaus/3d-ken-burns#51]
Traceback (most recent call last):
  File "/data/home/v_lifengmei/anaconda3/envs/ken/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 438, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 101, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 111, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 56, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autozoom.py", line 88, in <module>
    'objFrom': objFrom
  File "<string>", line 116, in process_autozoom
  File "<string>", line 433, in render_pointcloud
  File "cupy/util.pyx", line 81, in cupy.util.memoize.decorator.ret
  File "<string>", line 296, in launch_kernel
  File "/data/home/v_lifengmei/anaconda3/envs/ken/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 287, in compile_with_cache
    extra_source, backend)
  File "/data/home/v_lifengmei/anaconda3/envs/ken/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 339, in _compile_with_cache_cuda
    ptx = compile_using_nvrtc(source, options, arch, name + '.cu')
  File "/data/home/v_lifengmei/anaconda3/envs/ken/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 147, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/data/home/v_lifengmei/anaconda3/envs/ken/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 442, in compile
    raise CompileException(log, self.src, self.name, options, 'nvrtc')
cupy.cuda.compiler.CompileException: /tmp/tmpmblxzzzw/a2d1608f61e34b593ec1dcda48d72df5_2.cubin.cu(56): catastrophic error: cannot open source file "cuda_runtime.h"

1 catastrophic error detected in the compilation of "/tmp/tmpmblxzzzw/a2d1608f61e34b593ec1dcda48d72df5_2.cubin.cu".
Compilation terminated.

i sure that cuda_runtime.h is under my cuda root

**Comment by sniklaus** [comment]
The following first defines `CUDA_HOME` heuristically in case it isn't already defined (`CUDA_HOME` is an environment variable). It will then add `CUDA_HOME` and `CUDA_HOME/include` as an include folder for compiling the CUDA kernels kernels. In your case, there is neither  a `CUDA_HOME/cuda_runtime.h` nor a `CUDA_HOME/include/cuda_runtime.h` so you will have to make sure your environment is setup correctly.

https://github.com/sniklaus/3d-ken-burns/blob/a97a802f0d99fb16398caf641c764bb55f377080/common.py#L291-L297
