### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_function'

### ISSUE THREAD

**Issue by momalave** [sniklaus/3d-ken-burns#57]
When running "python autozoom.py --in ./images/doublestrike.jpg --out ./autozoom.mp4", I get the following error:

Traceback (most recent call last):
  File "autozoom.py", line 89, in <module>
    'objFrom': objFrom
  File "<string>", line 116, in process_autozoom
  File "<string>", line 433, in render_pointcloud
  File "cupy/_util.pyx", line 67, in cupy._util.memoize.decorator.ret
  File "<string>", line 296, in launch_kernel
AttributeError: 'NoneType' object has no attribute 'get_function'

Any thoughts for how to fix this?

**Comment by sniklaus** [comment]
You are hitting this bug in CuPy which you should be able to resolve be using an older CuPy version: https://github.com/cupy/cupy/issues/6231

**Comment by momalave** [comment]
Thanks for the quick response! I will try using an older version of cupy.
