### ISSUE TITLE
Compilation error on rocm-cupy framework (AMD GPU)

### ISSUE THREAD

**Issue by danielsz** [sniklaus/3d-ken-burns#68]
Managed to run the project in the cloud, but on a local machine with AMD GPU I get a compilation error. I've [reported](https://github.com/cupy/cupy/issues/7504) the problem on the appropriate repository, but I want to leave this here for future reference. Also, I would love to know if there is a workaround so that I can run this amazing project locally. Thank you!

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 686, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 154, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 166, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 84, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: HIPRTC_ERROR_COMPILATION (6)

```

**Comment by danielsz** [comment]
Ideally this shouldn't require you to do anything special. The requirements of this project (cupy, pytorch) have experimental support for rocm, the cuda equivalent on AMD systems. Which explains why I am able to run the PyTorch [examples](https://github.com/pytorch/examples) without any kind of modification. Unfortunately, it seems that some code in this project is not handled well by the compatibility layer, hence the wording _experimental support_ . It makes me sad, but not all is lost. I've reported the problem on cupy. I keep my hopes in check, because my GPU card is not officially supported by rocm. 

From the rocm [FAQ](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/markdown/hip_faq.md):

**Is HIP a drop-in replacement for CUDA?**

> No. HIP provides porting tools which do most of the work to convert CUDA code into portable C++ code that uses the HIP APIs. Most developers will port their code from CUDA to HIP and then maintain the HIP version. HIP code provides the same performance as native CUDA code, plus the benefits of running on AMD platforms.

**Comment by sniklaus** [comment]
Note that I am under the impression that the official PyTorch examples do not have inline CUDA like in [our project](https://github.com/sniklaus/3d-ken-burns/blob/774f58e475d1b490ceeac645aa3255bd139fdc00/common.py#L350-L436). And from your quote from the FAQ it seems like that that CUDA code would first have to be converted to HIP.

**Comment by danielsz** [comment]
Oh, sorry I didn't realize it was inline code. In that case, the problem is understood. Is the inline code absolutely necessary, the APIs don't have enough coverage?

**Comment by sniklaus** [comment]
I am afraid so, there are a bunch of operators that we rely on that are neither in PyTorch nor in CuPy.

**Comment by danielsz** [comment]
Oh well, never mind then. And thank you! 
Hopefully, this discussion may serve someone at any time.
